
-- This table will store chat message type Ex Text,File,Audio & Video
CREATE TABLE CHAT_MESSAGE_TYPE (
    ID                      SERIAL PRIMARY KEY,
    MESSAGE_TYPE            VARCHAR(100) NOT NULL
);

-- This table will store user all chat
CREATE TABLE USER_CHAT (
    CHAT_ID            VARCHAR(20) NOT NULL,
    SENDER_PROFILE_ID  VARCHAR(20) NOT NULL,
    RECEIVER_PROFILE_ID VARCHAR(20) NOT NULL,
    MESSAGE_TYPE       VARCHAR(200) NOT NULL,  -- Fixed typo from 'MESSGAE_TYPE'
    CREATION_DATETIME  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (CHAT_ID),
    FOREIGN KEY (MESSAGE_TYPE) REFERENCES CHAT_MESSAGE_TYPE (ID) ON DELETE CASCADE
);

-- This table will store user all text and emoji chat
CREATE TABLE USER_CHAT_TEXT (
    CHAT_ID           VARCHAR(20) NOT NULL,
    MESSAGE           VARCHAR(200) NOT NULL,  -- Fixed typo from 'MESSGAE'
    CREATION_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CHAT_ID) REFERENCES USER_CHAT (CHAT_ID) ON DELETE CASCADE
);

-- This table will store user all file chat
CREATE TABLE USER_CHAT_FILE (
    CHAT_ID           VARCHAR(20) NOT NULL,
    FILE_TYPE         VARCHAR(200) NOT NULL,
    FILE_LOCATION     VARCHAR(2000) NOT NULL,
    CREATION_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CHAT_ID) REFERENCES USER_CHAT (CHAT_ID) ON DELETE CASCADE
);
